### ISSUE TITLE
Game crashes as iframe

### ISSUE THREAD

**Issue by wp2000x** [Vanilagy/MarbleBlast#10]
Hi,

i wanted to put this game on my website in an iframe but notcied it crashes when it is put into it.

Example: https://jsfiddle.net/yamochnw/
Could this get fixed? Thank you

**Comment by Vanilagy** [comment]
It's throwing a DOMException: Failed to execute 'getLayoutMap' on 'Keyboard': getLayoutMap() must be called from a top-level browsing context.

Seems like iframes don't have sufficient access to features to be able to run this website. I think that's okay, as it was never intended to be embeddable.
