### ISSUE TITLE
Physics

### ISSUE THREAD

**Issue by main-gi** [Vanilagy/MarbleBlast#12]
Physics
<sup><sup><sup><sup><sup><sup><sup><sup><sup>yes this is a pooppost</sup></sup></sup></sup></sup></sup></sup></sup></sup>

**Comment by Vanilagy** [comment]
what is this + L + ratio + wrong + get a job + unfunny + you fell off + never liked you anyway + cope + ur allergic to gluten + don't care + cringe ur a kid + literally shut the fuck up + galileo did it better + your avi was made in MS Excel + ur bf is kinda ugly + i have more subscribers + owned + ur a toddler + reverse double take back + u sleep in a different bedroom from your wife + get rekt + i said it better + u smell + copy + who asked + dead game + seethe + ur a coward + stay mad + you main yuumi + aired + you drive a fiat 500 + the hood watches xqc now + yo mama + ok + currently listening to rizzle kicks without u. plus ur mind numbingly stupid plus ur voice is ronald mcdonald

**Comment by RandomityGuy** [comment]
I care + I asked + smile about it
stay glad + W + mald seethe cope less + not basic + skill + rational + you fell up + no audacity + triggeredn't + you got a life + ok slight_smile + not cringe + touched grass white_check_mark+ based + funny + laughed + grammar good + you're good + not reported + GG

https://youtu.be/sAoxJ8COphw
