### ISSUE TITLE
Older system compatibility

### ISSUE THREAD

**Issue by ilikemacsalot** [Vanilagy/MarbleBlast#13]
Can you make the game work on older browsers?

**Comment by Vanilagy** [comment]
Can you specify which browsers you're talking about? If you're talking about Safari < 12, I don't think I can support that. Safari is already a pain in the ass to support as it's always late to add features other browsers have had for years. It's just that without some modern features, this site doesn't work. 🤷‍♂️

**Comment by ilikemacsalot** [comment]
Chrome 49, Firefox 48, and Opera 37

**Comment by ilikemacsalot** [comment]
On 10.7.5

**Comment by Calinou** [comment]
I'm pretty sure recent versions of three.js and other dependencies no longer support the browser versions you mentioned, so this isn't technically feasible.

**Comment by Vanilagy** [comment]
Marble Blast Web does not run on three.js anymore, but I've tested my own renderer on plenty of desktop and mobile devices and decided that Safari 12 is the lowest I'm willing to go :P
