### ISSUE TITLE
Marble Blast Gold link

### ISSUE THREAD

**Issue by Growlithium** [Vanilagy/MarbleBlast#20]
The website links you to Platinum by default, and the only way to get to Gold is by clicking the button in the top left. I wanted to share the Marble Blast Gold port with my friends. Is there a way to get a direct link to the Marble Blast Gold port rather than Platinum? Would be nice :)

**Comment by Vanilagy** [comment]
I could add a little query param flag which directs to MBG directly, like `/?mbg`. Should be easy to do. The reason I boot into MBP by default is because it has everything MBG has + more.

**Comment by Vanilagy** [comment]
Here, this works now:

https://marbleblast.vani.ga/?mbg
